task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13
  name: Build - macOS Apple Silicon
  only_if: $CIRRUS_REPO_OWNER == 'Nheko-Reborn'
  environment:
    GITLAB_TRIGGER_TOKEN: ENCRYPTED[!5fb4bbdecbde3b2c766ac7383dca573cd5ec8b815c5ac9bede0cadfe9ad70ecd3e64b1728f7840da087099f3fc1fd4f7!]
  homebrew_script:
    - brew bundle --file .ci/macos/Brewfile
  build_script:
    - export PATH="$(brew --prefix qt5)/bin/:${PATH}"
    - export CMAKE_PREFIX_PATH="$(brew --prefix qt5)"
    - echo "$(brew --prefix qt5)"
    - cmake -GNinja -S. -Bbuild
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DCMAKE_INSTALL_PREFIX=.deps/usr
        -DHUNTER_ROOT="../.hunter"
        -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHUNTER_CONFIGURATION_TYPES=RelWithDebInfo
        -DUSE_BUNDLED_OPENSSL=ON
        -DQT_PATH="$(brew --prefix qt5)",
        -DQt5_DIR:PATH="$(brew --prefix qt5)/lib/cmake/Qt5",
        -DQt5MacExtras_DIR:PATH="$(brew --prefix qt5)/lib/cmake/Qt5MacExtras",
        -DQt5DBus_DIR:PATH="$(brew --prefix qt5)/lib/cmake/Qt5DBus",
        -DQt5QuickCompiler_DIR:PATH="$(brew --prefix qt5)/lib/cmake/Qt5QuickCompiler",
        -DCI_BUILD=ON
        -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15
    - cmake --build build
    - (cd build && git clone https://github.com/Nheko-Reborn/qt-jdenticon.git && cd qt-jdenticon && qmake && make -j 4 && cp libqtjdenticon.dylib ../nheko.app/Contents/MacOS)
  zip_script:
    - zip -r build/nheko.zip build/nheko.app
  gitlab_script:
    - curl -X POST
        --fail
        -F token="${GITLAB_TRIGGER_TOKEN}"
        -F ref="${CIRRUS_BRANCH}"
        -F "variables[TRIGGER_BUILD_ID]=${CIRRUS_BUILD_ID}"
        "https://nheko.im/api/v4/projects/2/trigger/pipeline"
  binaries_artifacts:
    path: build/nheko.zip