task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13
  name: Build - macOS Apple Silicon
  environment:
    GITLAB_TRIGGER_TOKEN: ENCRYPTED[!5fb4bbdecbde3b2c766ac7383dca573cd5ec8b815c5ac9bede0cadfe9ad70ecd3e64b1728f7840da087099f3fc1fd4f7!]
  matrix:
    - name: Homebrew
      homebrew_Script: brew bundle --file .ci/macos/Brewfile
    - name: Build
      build_script:
      - export PATH="$(brew --prefix qt5)/bin/:${PATH}"
      - ./.ci/macos/build.sh
    - name: Zip
      depends_on:
      - Build
      zip_script:
      - ditto -c -k --sequesterRsrc --keepParent build/nheko.app build/nheko.zip
    - name: Gitlab
      only_if: $CIRRUS_BRANCH == 'master'
      depends_on:
      - Zip
      gitlab_script:
        - curl -X POST
          --fail
          -F token="${GITLAB_TRIGGER_TOKEN}"
          -F ref="${CIRRUS_BRANCH}"
          -F "variables[TRIGGER_BUILD_ID]=${CIRRUS_BUILD_ID}"
          -F "variables[TRIGGERED_BY]=cirrus"
          "https://nheko.im/api/v4/projects/2/trigger/pipeline"
  binaries_artifacts:
    path: build/nheko.zip  