variables:
  CCACHE_COMPILERCHECK: content
  CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
  # prevent configure tzdata hanging apt install commands
  DEBIAN_FRONTEND: noninteractive

stages:
  - prepare
  - build
  - deploy

prepare-gcc9-image:
  stage: prepare
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: [docker]
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - .ci/gcc-9/Dockerfile
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --whitelist-var-run=false --context $CI_PROJECT_DIR/.ci/gcc-9 --dockerfile $CI_PROJECT_DIR/.ci/gcc-9/Dockerfile --destination $CI_REGISTRY_IMAGE/gcc-9:latest

build-gcc9-meson:
  stage: build
  image: $CI_REGISTRY_IMAGE/gcc-9:latest
  tags: [docker]
  needs:
    - job: prepare-gcc9-image
      optional: true
  variables:
    QT_PKG: 515
    TRAVIS_OS_NAME: linux
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - . "/opt/qt${QT_PKG}/bin/qt${QT_PKG}-env.sh" || true
  script:
    - meson setup builddir
    - meson compile -C builddir
  cache:
    key: "$CI_JOB_NAME"
    when: 'always'
    paths:
      - .ccache
      - subprojects/packagecache/

build-gcc9:
  stage: build
  image: $CI_REGISTRY_IMAGE/gcc-9:latest
  tags: [docker]
  needs:
    - job: prepare-gcc9-image
      optional: true
  variables:
    QT_PKG: 515
    TRAVIS_OS_NAME: linux
  before_script:
    - wget https://github.com/Kitware/CMake/releases/download/v3.19.0/cmake-3.19.0-Linux-x86_64.sh && sh cmake-3.19.0-Linux-x86_64.sh  --skip-license  --prefix=/usr/local
    - rm -rf ../.hunter &&  mv .hunter ../.hunter || true
    - . "/opt/qt${QT_PKG}/bin/qt${QT_PKG}-env.sh" || true
  script:
    - export PATH="/usr/local/bin/:/usr/lib/ccache:${PATH}"
    - export CMAKE_BUILD_PARALLEL_LEVEL=$(cat /proc/cpuinfo | awk '/^processor/{print $3}' | wc -l)
    - cmake -GNinja -H. -Bbuild
        -DCMAKE_INSTALL_PREFIX=.deps/usr
        -DHUNTER_ROOT="../.hunter"
        -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF -DUSE_BUNDLED_OPENSSL=ON -DUSE_BUNDLED_LMDB=OFF
        -DVOIP=OFF
        -DCMAKE_BUILD_TYPE=Release -DHUNTER_CONFIGURATION_TYPES=Release
        -DCI_BUILD=ON -DFETCHCONTENT_QUIET=OFF
    - cmake --build build
  after_script:
    - mv ../.hunter .hunter
  cache:
    key: "$CI_JOB_NAME"
    when: 'always'
    paths:
      - .hunter/
      - .ccache

build-macos:
  stage: build
  tags: [macos]
  before_script:
    #- brew update
    #- brew reinstall --force python3
    #- brew bundle --file=./.ci/macos/Brewfile --force --cleanup
    - rm -rf ../.hunter &&  mv .hunter ../.hunter || true
  needs: []
  script:
    - export PATH=/usr/local/opt/qt@5/bin/:${PATH}
    - export CMAKE_PREFIX_PATH=/usr/local/opt/qt@5
    - cmake -GNinja -H. -Bbuild
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DCMAKE_INSTALL_PREFIX=.deps/usr
        -DHUNTER_ROOT="../.hunter"
        -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHUNTER_CONFIGURATION_TYPES=RelWithDebInfo
        -DUSE_BUNDLED_OPENSSL=ON
        -DUSE_BUNDLED_BOOST=ON
        -DCI_BUILD=ON
    - cmake --build build
    - (cd build && git clone https://github.com/Nheko-Reborn/qt-jdenticon.git && cd qt-jdenticon && qmake && make -j 4 && cp libqtjdenticon.dylib ../nheko.app/Contents/MacOS)
  after_script:
    - mv ../.hunter .hunter
  artifacts:
    paths:
      - build/nheko.app
    name: nheko-${CI_COMMIT_SHORT_SHA}-macos-app
    expose_as: 'macos-app'
    public: false
  cache:
    key: "${CI_JOB_NAME}"
    when: 'always'
    paths:
      - .hunter/
      - "${CCACHE_DIR}"

build-macos-meson:
  stage: build
  tags: [macos]
  needs: []
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - export PATH=/usr/local/opt/qt@5/bin/:${PATH}
    - meson setup --prefix=${PWD}/build/nheko.app --bindir=Contents/MacOS --buildtype=debugoptimized build
    - meson compile -C build
    - meson install --skip-subprojects -C build
  artifacts:
    paths:
      - build/nheko.app
    name: nheko-${CI_COMMIT_SHORT_SHA}-macos-app
    expose_as: 'macos-app'
    public: false
  cache:
    key: "$CI_JOB_NAME"
    when: 'always'
    paths:
      - .ccache
      - subprojects/packagecache/

codesign-macos:
  stage: deploy
  tags: [macos]
  before_script:
    - pip3 install dmgbuild
  script:
    - export PATH=/usr/local/opt/qt@5/bin/:${PATH}
    - ./.ci/macos/notarize.sh
  after_script:
    - ./.ci/upload-nightly-gitlab.sh artifacts/nheko-${CI_COMMIT_SHORT_SHA}.dmg
  needs:
    - build-macos-meson
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if : $CI_COMMIT_TAG
  artifacts:
    paths:
      - artifacts/nheko-${CI_COMMIT_SHORT_SHA}.dmg
    name: nheko-${CI_COMMIT_SHORT_SHA}-macos
    expose_as: 'macos-dmg'


build-flatpak-amd64:
  stage: build
  image: ubuntu:latest
  #image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
  tags: [docker]
  needs: []
  before_script:
    # need flatpak 1.11.1 at least
    - apt-get update && apt-get install -y software-properties-common
    - add-apt-repository ppa:alexlarsson/flatpak && apt-get update && apt-get -y install flatpak-builder git python curl python3-aiohttp python3-tenacity gir1.2-ostree-1.0
    - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak --noninteractive install --user flathub org.kde.Platform//5.15
    - flatpak --noninteractive install --user flathub org.kde.Sdk//5.15
  script:
    - export VERSION=$(git describe)
    - mkdir -p build-flatpak
    - cd build-flatpak
    - flatpak-builder --user --disable-rofiles-fuse --ccache --repo=repo --default-branch=${CI_COMMIT_REF_NAME//\//_} --subject="Build of Nheko ${VERSION} `date`" app ../io.github.NhekoReborn.Nheko.yaml
    - flatpak build-bundle repo nheko-amd64.flatpak io.github.NhekoReborn.Nheko ${CI_COMMIT_REF_NAME//\//_}
  after_script:
    - (cd ./scripts && ./upload-to-flatpak-repo.sh ../build-flatpak/repo) || true
    - bash ./.ci/upload-nightly-gitlab.sh build-flatpak/nheko-amd64.flatpak
  cache:
    key: "$CI_JOB_NAME"
    when: 'always'
    paths:
      - build-flatpak/.flatpak-builder/
  artifacts:
    expose_as: 'flatpak-amd64'
    paths: ['build-flatpak/nheko-amd64.flatpak']
    name: flatpak-${CI_COMMIT_REF_NAME}-${VERSION}-amd64

build-flatpak-arm64:
  stage: build
  image: ubuntu:latest
  #image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
  tags: [docker-arm64]
  needs: []
  before_script:
    # need flatpak 1.11.1 at least
    - apt-get update && apt-get install -y software-properties-common
    - add-apt-repository ppa:alexlarsson/flatpak && apt-get update && apt-get -y install flatpak-builder git python curl python3-aiohttp python3-tenacity gir1.2-ostree-1.0
    - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak --noninteractive install --user flathub org.kde.Platform//5.15
    - flatpak --noninteractive install --user flathub org.kde.Sdk//5.15
  script:
    - export VERSION=$(git describe)
    - mkdir -p build-flatpak
    - cd build-flatpak
    - flatpak-builder --user --disable-rofiles-fuse --ccache --repo=repo --default-branch=${CI_COMMIT_REF_NAME//\//_} --subject="Build of Nheko ${VERSION} `date` for arm64" app ../io.github.NhekoReborn.Nheko.yaml
    - flatpak build-bundle repo nheko-arm64.flatpak io.github.NhekoReborn.Nheko ${CI_COMMIT_REF_NAME//\//_}
  after_script:
    - (cd ./scripts && ./upload-to-flatpak-repo.sh ../build-flatpak/repo) || true
    - bash ./.ci/upload-nightly-gitlab.sh build-flatpak/nheko-arm64.flatpak
  cache:
    key: "$CI_JOB_NAME"
    when: 'always'
    paths:
      - build-flatpak/.flatpak-builder/
  artifacts:
    expose_as: 'flatpak-arm64'
    paths: ['build-flatpak/nheko-arm64.flatpak']
    name: flatpak-${CI_COMMIT_REF_NAME}-${VERSION}-arm64

build-windows-meson:
  stage: build
  image: win10-base
  tags: [windows]
  variables:
    BUILD: ${CI_BUILDS_DIR}
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - PATH=${PATH##/usr/local/bin:/usr/bin:/bin:} ./.ci/windows/build-meson.cmd
    - ls -la
  after_script:
    - PATH=${PATH##/usr/local/bin:/usr/bin:/bin:} ./.ci/windows/deploy-meson.cmd
  cache:
    key: "$CI_JOB_NAME"
    when: 'always'
    paths:
      - subprojects/packagecache/

linting:
  stage: build
  image: alpine:latest
  tags: [docker]
  needs: []
  before_script:
    - apk update && apk add clang-extra-tools make git python3 py3-pip
    - export PATH="$PATH:/root/.local/bin"
    - pip3 install --user reuse
  script:
    - make lint
    - make license

