language: cpp
sudo: required
dist: trusty

notifications:
  webhooks:
    urls:
    - https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHJlZF9za3klM0FvY2Vhbi5qb2Vkb25vZnJ5LmNvbS8lMjFldkFxa1BIWnVQSElHZWVuaGklM0FvY2Vhbi5qb2Vkb25vZnJ5LmNvbQ
    on_success: always
    on_failure: always
    on_start: never
  email: false

matrix:
    include:
        - os: osx
          osx_image: xcode9
          compiler: clang
          env:
              - DEPLOYMENT=1
              - USE_BUNDLED_BOOST=0
              - USE_BUNDLED_CMARK=0
        - os: linux
          compiler: gcc
          env:
              - CXX_COMPILER=g++-5
              - C_COMPILER=gcc-5
              - QT_VERSION="-5.10.1"
              - QT_PKG=510
              - DEPLOYMENT=1
              - USE_BUNDLED_BOOST=1
              - USE_BUNDLED_CMARK=1
          addons:
              apt:
                  sources: ["ubuntu-toolchain-r-test"]
                  packages: ["g++-5", "ninja-build"]
        - os: linux
          compiler: gcc
          env:
              - CXX_COMPILER=g++-8
              - C_COMPILER=gcc-8
              - QT_VERSION=571
              - QT_PKG=57
              - USE_BUNDLED_BOOST=1
              - USE_BUNDLED_CMARK=1
          addons:
              apt:
                  sources: ["ubuntu-toolchain-r-test"]
                  packages: ["g++-8", "ninja-build"]
        - os: linux
          compiler: clang
          env:
              - CXX_COMPILER=clang++-5.0
              - C_COMPILER=clang-5.0
              - QT_VERSION=592
              - QT_PKG=59
              - USE_BUNDLED_BOOST=1
              - USE_BUNDLED_CMARK=1
          addons:
              apt:
                  sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"]
                  packages: ["clang-5.0", "g++-7", "ninja-build"]

before_install:
    - export CXX=${CXX_COMPILER}
    - export CC=${C_COMPILER}
    # Use TRAVIS_TAG if defined, or the short commit SHA otherwise
    - export VERSION=${TRAVIS_TAG:-$(git rev-parse --short HEAD)}
install:
    - ./.ci/install.sh
    - export PATH=/usr/local/bin:${PATH}

script:
    - ./.ci/script.sh
    - sed -i -e "s/VERSION_NAME_VALUE/${VERSION}/g" ./.ci/bintray-release.json || true
    - cp ./.ci/bintray-release.json .
deploy:
- provider: bintray
  user: "redsky17"
  key:
    secure: "2C+ESOClZdNCDzfUfE8Rcdn9+BM3/5x1lebGS0qRxICMAuylx50C8RAxlqKIFNI1J+IMnj5xhK+1oWsLg6wUdo8B3JocvM6P1NbC/WwfY5UJVwtSmzcqvEC+IjM90Bng8OoM5f6ED3IAUyYPBgo8J14+2l5Oruvr99t0mrpniLXDf66TJrI9u/+05JYa2pm0EWlQkDVaziI+96zAt1pMIX9Z/ToTmUbq2OAlHaN8H4hR5aBRmYuF11FQVyARK64eqRsBV4RXKJ9DjW7BR+pQV008hQUoXrCxK8xIf/Qph9h1fz63961NJxfru62LeuZ4Z8MUcV9L+p0HYZzkhNdn5Z3QFf3SXbrVCYs6LK6+uKHpmYS7vB5XwjDx9SWc2szsd5OVKJg3YEdBcC4KUSL3VEbBHDSQ3GFsVKoBsZvopwHkyCmPotY47HtEiPBLdEcsOvcVyeU5Gfq9EOp9dB+nJbNrujBgav1l13CorkBG2rgD+NRivV1otclXnPsIj85ySrc6xk0VDN3zogLAdLw0f+fNOaK17N8GmhPbCu/iX2Vjem/fdjh4NPC4pSNDei2MoWUfqGBmoTxuQEsZeywigwV2c51W9RZuwo8X810N3ehVcBmmNyLjbKmYT+8Kp+dJbaf/ErFnvdZl06mX2bgyxFakv5iQY3dwX4WYHvl77c4="
  skip_cleanup: true
  overwrite: true
  file: bintray-release.json
  on:
    condition: "$DEPLOYMENT == 1"
    repo: Nheko-Reborn/nheko
    tags: false
    all_branches: true
    deploy: 
- skip_cleanup: true
  overwrite: true
  provider: releases
  api_key:
    secure: "JROFCxI1Dj0j8GKftCk1M16PovGmbCQb/i6JKm+YKWIhoYoMJBFl3TzhN0D0KlT8VeClZ0WV4MOom6elAkxlYTGR1kcoJ5ESt/AS0B1ULxq2exbmqzqJgJJBb65JVo4nglLHZPnUHOY5s/QGtg05nPeexcK8b3lFvhMRI+Y5jqX9i4FGsEBk6tG2OLfXB0odU8f6rhEeIGWgJw1LVyiTk3VoQcJtBi7Vsg3p4othMaLDlkVHsepNY+xSO14NbNpUjXSzYWZJEM9HqCOaOlAjZR5Q0Ad365TqN9zj6NOVwxEdN4Zl3/Ux838Or6TobhdhGjqqO2JmWt6C+xV4XJ9wX+8LPb+hYYVBrItp32g3grtW/e4nNsp4j3nm1P87kzKPxC4oAaskyn0dlwC4Vo3LH67beQiceAIuM9ywej4Zwr94+MeKjIVtqI6Qz7Tjlt1pFGI1lmfkKQOXiFlkwPbyCPV3smpJ1WSOC4Npkht6tFPBlLV2DFySYUMRAdH2RwBxWhjzwsSJlx/dEKUUL5yffKtg2tANM6aCCyXMEqEXXVkFe9e9ymPbGmmQuf56xo3rYQj5BcQWA9JHAancqLkxoR0rbRBBmai5qDQP7rBss/HR7Uec5xSnYkS6YYI9zpZ+FTfPa7lnVI3c8hj+ukua1EnsYytB8F8l95jrO8fnTxU="
  file_glob: true
  file:
  - nheko-${VERSION}-x86_64.AppImage
  on:
    condition: "$TRAVIS_OS_NAME == linux && $DEPLOYMENT == 1"
    repo: Nheko-Reborn/nheko
    tags: true
- skip_cleanup: true
  overwrite: true
  provider: releases
  api_key:
    secure: "JROFCxI1Dj0j8GKftCk1M16PovGmbCQb/i6JKm+YKWIhoYoMJBFl3TzhN0D0KlT8VeClZ0WV4MOom6elAkxlYTGR1kcoJ5ESt/AS0B1ULxq2exbmqzqJgJJBb65JVo4nglLHZPnUHOY5s/QGtg05nPeexcK8b3lFvhMRI+Y5jqX9i4FGsEBk6tG2OLfXB0odU8f6rhEeIGWgJw1LVyiTk3VoQcJtBi7Vsg3p4othMaLDlkVHsepNY+xSO14NbNpUjXSzYWZJEM9HqCOaOlAjZR5Q0Ad365TqN9zj6NOVwxEdN4Zl3/Ux838Or6TobhdhGjqqO2JmWt6C+xV4XJ9wX+8LPb+hYYVBrItp32g3grtW/e4nNsp4j3nm1P87kzKPxC4oAaskyn0dlwC4Vo3LH67beQiceAIuM9ywej4Zwr94+MeKjIVtqI6Qz7Tjlt1pFGI1lmfkKQOXiFlkwPbyCPV3smpJ1WSOC4Npkht6tFPBlLV2DFySYUMRAdH2RwBxWhjzwsSJlx/dEKUUL5yffKtg2tANM6aCCyXMEqEXXVkFe9e9ymPbGmmQuf56xo3rYQj5BcQWA9JHAancqLkxoR0rbRBBmai5qDQP7rBss/HR7Uec5xSnYkS6YYI9zpZ+FTfPa7lnVI3c8hj+ukua1EnsYytB8F8l95jrO8fnTxU="
  file: nheko-${VERSION}.dmg
  on:
    condition: "$TRAVIS_OS_NAME == osx && $DEPLOYMENT == 1"
    repo: Nheko-Reborn/nheko
    tags: true