version: 0.1.0-{build}

environment:
    global:
        MSYSTEM: "MINGW64"

platform: x64

configuration:
    - Release

build:
  verbosity: minimal

install:
    - set QT_DIR=C:\Qt\5.8\msvc2015_64
    - set PATH=%PATH%;%QT_DIR%\bin;C:\MinGW\bin

build_script:
    - cmake -G "Visual Studio 14 2015 Win64" -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
    - ls -lh build

after_build:
    - mkdir NhekoRelease
    - copy build\Debug\nheko.exe NhekoRelease\nheko.exe
    - windeployqt --release NhekoRelease\nheko.exe
    - 7z a nheko_win_64.zip .\NhekoRelease\*

artifacts:
    - path: nheko_win_64.zip
    - path: NhekoRelease\nheko.exe
