# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - releases/*

pr:
  - master
  - releases/*

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      CXX_COMPILER: 'clang++-6.0'
      C_COMPILER: 'clang-6.0'
      QT_VERSION: '5.11.1'
      QT_PKG: '511'
      DEPLOYMENT: '1'
      USE_BUNDLED_BOOST: '1'
      USE_BUNDLED_CMARK: '1'
      USE_BUNDLED_JSON: '1'
      TRAVIS_OS_NAME: 'linux'
    steps:
    - template: .ci/azure-build.yml
      parameters:
        osName: 'linux'

  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    variables:
      DEPLOYMENT: '1'
      USE_BUNDLED_BOOST: '0'
      USE_BUNDLED_CMARK: '0'
      USE_BUNDLED_JSON: '0'
      TRAVIS_OS_NAME: 'osx'
    steps:
    - template: .ci/azure-build.yml
      parameters:
        osName: 'osx'

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      TRAVIS_OS_NAME: 'windows'
    steps:
    - template: .ci/azure-build.yml
      parameters:
        osName: 'windows'