# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - releases/*

pr:
  - master
  - releases/*

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - template: .ci/azure-build.yml

  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - template: .ci/azure-build.yml

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    
    steps:
    - template: .ci/azure-build.yml